apiVersion: v1
kind: Pod
metadata:
  name: cpupod-exclusive
spec:
  containers:
  - name: cputest-exclusive
    command: [ /thread_busyloop ]
    args: ["-c","$(EXCLUSIVE_CPUS)"]
    image: busyloop
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
      limits:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
